### ISSUE TITLE
Arp will fill in blank on failure

### ISSUE THREAD

**Issue by deavmi** [deavmi/twine#1]
Because of how the **niknaks** `CacheMap` works, if we fail to resolve ARP we **must** till return the value for the key (in this case the key is a `Target` and the value is an `isEmpty()` or `empt()`'d `ArpEntry`).

We therefore need niknaks to support a sort of abortion.

---

I dislike that last sentence a lot.

**Comment by deavmi** [comment]
Nvm, this is BS

**Comment by moonsuyoung** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
broker, @luna0607, @JustinG1552, @lolita1992, @Eloco, @CRYP70N1C4, @AnJa-zhang, @wangweiai, @Mlncholy, @cisary, @paddyzab, @firstrose, @arunsunner, @youpas, @ripper2hl, @com63, @h3nill, @kkxxxxxxx, @hhktony, @fdxxw, @airkingZy, @heijie730, @scriptsman, @ovaldi, @hgoldfish, @brizzbane, @ixenos, @lennonhe, @andreichernov, @qiaoshun8888, @fanandactuaility, @sanjinhub, @TheAkatsuki, @alete89, @stefenforli, @c0d3x7, @shede333, @Ink-33, @zanetu, @n37r06u3, @celrenheit, @pseudonym0, @mrrva, @joetm, @soujhony, @gasbakid, @dbsGen, @Loofer, @shubidubapp, @jake-fleming
